RUN curl --verbose https://nodejs.org/dist/latest-v8.x/node-v8.10.0-linux-armv6l.tar.gz | tar -zx --directory /usr/ --strip-components=1 &&\
	curl --verbose https://dl.google.com/go/go1.10.linux-armv6l.tar.gz | tar -C /usr/local -xz 

